name: Lint PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  lint-pr-title:
    name: Lint PR Title
    uses: the-i-engineers/infrastructure/.github/workflows/lint-pr-title.yml@v2.12.5
    permissions:
      pull-requests: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
